services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: amrs-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - amrs-network

  sidecar:
    build: ./sidecar
    container_name: amrs-sidecar
    restart: unless-stopped
    environment:
      POSTGRES_HOST: amrs-postgres
      POSTGRES_PORT: ${POSTGRES_CONTAINER_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      QDRANT_HOST: amrs-qdrant
      QDRANT_PORT: 6333
      OLLAMA_HOST: ${OLLAMA_HOST}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - amrs-network

  backend:
    build: ./backend
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_CONTAINER_PORT}
      POSTGRES_HOST: amrs-postgres
      REDIS_HOST: amrs-redis
      REDIS_PORT: ${REDIS_PORT}
      SIDECAR_URL: http://amrs-sidecar:8000
      OLLAMA_HOST: ${OLLAMA_HOST}
      OLLAMA_MODEL: ${OLLAMA_MODEL}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - amrs-network

  postgres:
    image: postgres:18.4
    container_name: amrs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/18/docker
      # POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - amrs-network

  redis:
    image: redis:8.8.0
    container_name: amrs-redis
    restart: unless-stopped
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - amrs-network

  qdrant:
    image: qdrant/qdrant:v1.17.0
    container_name: amrs-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "http://localhost:6333/healthz"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 20s
    networks:
      - amrs-network

volumes:
  postgres_data:
  redis_data:
  qdrant_data:

networks:
  amrs-network:
    driver: bridge